import { Body, Controller, Get, Post } from '@nestjs/common';
import { ApiOkResponse, ApiOperation, ApiTags } from '@nestjs/swagger';
import { AppService } from './app.service';
import { AiTestRequestDto, AiTestResponseDto } from './common/dtos/ai.dto';

@ApiTags('App')
@Controller()
export class AppController {
  constructor(private readonly appService: AppService) {}

  @Get()
  @ApiOperation({
    summary: 'Health check endpoint',
    description:
      'Returns a simple greeting to verify that the service is running.',
  })
  @ApiOkResponse({
    description: 'Service is reachable',
    schema: {
      type: 'string',
      example: 'Hello World!',
    },
  })
  getHello(): string {
    return this.appService.getHello();
  }

  @Post('ai/test')
  @ApiOperation({
    summary: 'AI query test',
    description:
      'Receives a prompt and returns an AI response generated by Gemini 2.0 Flash.',
  })
  @ApiOkResponse({
    description: 'AI query executed successfully',
    type: AiTestResponseDto,
  })
  async testAiQuery(
    @Body() request: AiTestRequestDto,
  ): Promise<AiTestResponseDto> {
    return await this.appService.testAiQuery(request);
  }
}
